// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.Tag;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AnsaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  @Tag("AcceptanceTest")
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  @Tag("AcceptanceTest")
  public void tearDown() {
    driver.quit();
  }
  @Test
  @Tag("AcceptanceTest")
  public void ansa() {
    driver.get("https://www.ansa.it/");
    driver.manage().window().setSize(new Dimension(870, 930));
    driver.findElement(By.cssSelector(".news:nth-child(1) > header a")).click();
    driver.findElement(By.cssSelector(".container:nth-child(16) #anysearch")).click();
    driver.findElement(By.cssSelector(".container:nth-child(16) #anysearch")).sendKeys("test");
    driver.findElement(By.cssSelector(".container:nth-child(16) #anysearch")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Ue a Musk, \'c\'è un enorme lavoro da fare contro la disinformazione\'")).click();
    driver.findElement(By.cssSelector(".brand:nth-child(1) .brand-logo-europa")).click();
  }
}
